SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ParentPortal].[LogAccess](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](128) NOT NULL,
	[EventDate] [datetime] NOT NULL,
	[USI] [int] NOT NULL,
	[UniqueId] [nvarchar](32) NOT NULL,
	[PersonType] [int] NOT NULL,
 CONSTRAINT [PK_LogAccess2] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO